name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Backend
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd ~/Kickoff
            git pull origin master
            cd backend
            npm install
            npm run build
            pm2 restart index

  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Frontend
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd ~/Kickoff
            git pull origin master
            cd frontend
            npm install
            npm run build